server:
  port: 9999
spring:
  application:
    name: blog-application
  datasource:
    url: jdbc:mysql://localhost:3306/MySpringSecurity?characterEncoding=utf-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    password: doper
    database: 2
    timeout: 2000ms
  kafka:
    producer:
      client-id: ${spring.application.name}-producer
      bootstrap-servers: kafka1:9091,kafka2:9092,kafka3:9093
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      buffer-memory: 33554432 #32M
      batch-size: 16384 # 16K
      acks: "-1"
      retries: 5
      properties:
        linger:
          ms: 5


mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: cn.doper.mybatis.entity
jwt:
  tokenHeader: Authorization #JWT存储的请求头
  secret: admin-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*24*7)


# 自定义redis信息
redis:
  key:
    user-cache-prefix: userCache  #用户信息key前缀
    user-cache-info: info
    permission-cache-prefix: permissionCache #用户权限前缀
  expire:
    common: 86400

# 自定义kafka
kafka:
  topic:
    user-login-log: user-login-log